### PR TITLE
Add pycord_examples

### PR DESCRIPTION
**Pull request by ephemeral8997**
The `PycordManager` object will have `pycord_examples` attribute which has all file names of pycord/examples, pycord/examples/app_commands and pycord_examples/views which can be used as choices for the `p.example` command.

### CODE REVIEW

**Comment by ephemeral8997** [comment]
I changed the /example command to a subclass of `SlashCommand` so we can wrap the callback and add `PycordManager.pycord_examples` as choices of option. All these changes have been comitted to this pull request, the only remaining issue is filenames are limited to 25 choices per option, and this isn't enough for [pycord/examples](https://github.com/Pycord-Development/pycord/tree/master/examples) sadly

**Comment by ephemeral8997** [comment]
I think we should use an embed to get the best results of the example found by regex.

**Comment by ephemeral8997** [comment]
Since Discord has limited the choices to only 25 choices per option, embeds can contain more content.

**Comment by Dorukyum** [comment]
Good idea, maybe not regex but kinda like `if search_string in example["name"]`

**Comment by ephemeral8997** [comment]
maybe the code should loop over the string and check if most letters match the example filename

**Comment by ephemeral8997** [comment]
I think it's better than checking if the whole name is inside the example name, since typos might be in the search string

**Comment by ephemeral8997** [comment]
I think It's ready for review

**Comment by ephemeral8997** [comment]
It's finally ready for review, everything should be good now.

**Comment by Dorukyum** [comment]
Added in #32, it was a simpler approach. Thanks anyways.

**Pull request closed without merging**
