### PR TITLE
better commands

### PR DESCRIPTION
**Pull request by rtk-rnjn**
**Better suggestion command(s).**

+ Members can now delete the suggestion (they suggested).
+ Moderators can flag or add note to the suggestion

---

**Better poll command**

+ Multiple options for the polling

### CODE REVIEW

**Comment by Dorukyum** [comment]
About the poll command: Wouldn't adding a ton of reactions spam the API?

**Comment by rtk-rnjn** [comment]
Didn't thought of it. We can add cooldowns. I guess, the command isn't used on wide scale (for now) so it kinda "ok".

**Comment by Dorukyum** [comment]
I think we can limit poll choice count to 5 for now, along with the cooldown.

**Comment by rtk-rnjn** [comment]
lots of conflicts...

**Pull request closed without merging**
