### PR TITLE
Add server logs

### PR DESCRIPTION
**Pull request by ephemeral8997**
This pr will add most audit logs events, It's still under working and testing for now.

### CODE REVIEW

**Comment by Dorukyum** [comment]
These look good at first glance but we have to implement guild checks on these and maybe add an extra "server_log" channel id field besides the already existing "mod_log". Related to #18.

I was also planning to move this type of logs to another cog to be able to unload/manage them seperately. This causes some issues because some log methods are used in this cog too so maybe the methods could be added to the Bot or the Context.

**Comment by Dorukyum** [comment]
Update: mod logs have been moved to cogs/modlogs.py
Not sure if these should also be there or a new cog should be created for them.

**Comment by ephemeral8997** [comment]
I should move the modlogs to cogs/modlogs.py firstly

**Comment by ephemeral8997** [comment]
I've moved the mod logs to `cogs/modlogs.py`, furthermore, `server_log` coroutine has been aded to handle most mod log events, and guild checks have been added too.

**Comment by ephemeral8997** [comment]
There is more mod log events that should be added, but some are not useful, I'll add more soon

**Review by Dorukyum — APPROVED** [review]
Thank you

**Pull request merged**
